// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs7Dq07Zyt0bnFFQYJleToBg13ZGof1L4',
    appId: '1:822191016343:web:84351e5926312e2acd9cd2',
    messagingSenderId: '822191016343',
    projectId: 'we-chat-d984f',
    authDomain: 'we-chat-d984f.firebaseapp.com',
    storageBucket: 'we-chat-d984f.appspot.com',
    measurementId: 'G-RNFC29MJQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-rU7brM02HL42trnboMhFLpW1asiY-MU',
    appId: '1:822191016343:android:5ad77797a70930f6cd9cd2',
    messagingSenderId: '822191016343',
    projectId: 'we-chat-d984f',
    storageBucket: 'we-chat-d984f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFAvdaxUzN4lJwvphsdtLrbn4cmee-f-0',
    appId: '1:822191016343:ios:9e819bd34bebb884cd9cd2',
    messagingSenderId: '822191016343',
    projectId: 'we-chat-d984f',
    storageBucket: 'we-chat-d984f.appspot.com',
    iosBundleId: 'com.kp2106.wechat.wechatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFAvdaxUzN4lJwvphsdtLrbn4cmee-f-0',
    appId: '1:822191016343:ios:9e819bd34bebb884cd9cd2',
    messagingSenderId: '822191016343',
    projectId: 'we-chat-d984f',
    storageBucket: 'we-chat-d984f.appspot.com',
    iosBundleId: 'com.kp2106.wechat.wechatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs7Dq07Zyt0bnFFQYJleToBg13ZGof1L4',
    appId: '1:822191016343:web:d3e99e982df7aec4cd9cd2',
    messagingSenderId: '822191016343',
    projectId: 'we-chat-d984f',
    authDomain: 'we-chat-d984f.firebaseapp.com',
    storageBucket: 'we-chat-d984f.appspot.com',
    measurementId: 'G-7CCPZSR8BM',
  );
}
